name: Docker

on:
  pull_request:
  push:
    branches:
      - master
  merge_group:
  release:
    types:
      - published

permissions:
  contents: read

jobs:
  ubuntu:
    if: github.repository_owner == 'Homebrew'
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        version: ["18.04", "20.04", "22.04", "24.04"]
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Fetch origin/master from Git
        run: git fetch origin master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@988b5a0280414f521da01fcc63a27aeeb4b104db # v3

      - name: Determine build attributes
        id: attributes
        run: |
          {
            echo "date=$(date --rfc-3339=seconds --utc)"
            echo "brew_version=$(git describe --tags --dirty --abbrev=7)"
          } | tee -a "${GITHUB_OUTPUT}"

      - name: Build Docker image
        uses: docker/build-push-action@5cd11c3a4ced054e52742c5fd54dca954e0edd85 # v6
        with:
          push: false
          tags: brew
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            version=${{ matrix.version }}
          labels: |
            org.opencontainers.image.created=${{ steps.attributes.outputs.date }}
            org.opencontainers.image.url=https://brew.sh
            org.opencontainers.image.documentation=https://docs.brew.sh
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.version=${{ steps.attributes.outputs.brew_version }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.vendor=${{ github.repository_owner }}
            org.opencontainers.image.licenses=BSD-2-Clause

      - name: Run brew test-bot --only-setup
        run: docker run --rm brew brew test-bot --only-setup

      - name: Log in to GitHub Packages
        if: >
          github.event_name == 'release' ||
          (github.event_name == 'push' && github.ref == 'refs/heads/master' &&
           matrix.version == '22.04')
        run: |
          docker login ghcr.io -u BrewTestBot --password-stdin <<<"$TOKEN"
        env:
          TOKEN: ${{secrets.HOMEBREW_BREW_GITHUB_PACKAGES_TOKEN}}

      - name: Log in to Docker Hub
        if: >
          github.event_name == 'release' ||
          (github.event_name == 'push' && github.ref == 'refs/heads/master' &&
           matrix.version == '22.04')
        run: |
          docker login -u brewtestbot --password-stdin <<<"$TOKEN"
        env:
          TOKEN: ${{secrets.HOMEBREW_BREW_DOCKER_TOKEN}}

      - name: Deploy the tagged Docker image to GitHub Packages
        if: github.event_name == 'release'
        run: |
          brew_version="${GITHUB_REF:10}"
          echo "brew_version=${brew_version}" >> "${GITHUB_ENV}"
          docker tag brew "ghcr.io/homebrew/ubuntu${{matrix.version}}:${brew_version}"
          docker push "ghcr.io/homebrew/ubuntu${{matrix.version}}:${brew_version}"
          docker tag brew "ghcr.io/homebrew/ubuntu${{matrix.version}}:latest"
          docker push "ghcr.io/homebrew/ubuntu${{matrix.version}}:latest"

      - name: Deploy the tagged Docker image to Docker Hub
        if: github.event_name == 'release'
        run: |
          docker tag brew "homebrew/ubuntu${{matrix.version}}:${brew_version}"
          docker push "homebrew/ubuntu${{matrix.version}}:${brew_version}"
          docker tag brew "homebrew/ubuntu${{matrix.version}}:latest"
          docker push "homebrew/ubuntu${{matrix.version}}:latest"

      - name: Deploy the homebrew/brew Docker image to GitHub Packages and Docker Hub
        if: github.event_name == 'release' && matrix.version == '22.04'
        run: |
          docker tag brew "ghcr.io/homebrew/brew:${brew_version}"
          docker push "ghcr.io/homebrew/brew:${brew_version}"
          docker tag brew "ghcr.io/homebrew/brew:latest"
          docker push "ghcr.io/homebrew/brew:latest"
          docker tag brew "homebrew/brew:${brew_version}"
          docker push "homebrew/brew:${brew_version}"
          docker tag brew "homebrew/brew:latest"
          docker push "homebrew/brew:latest"

      - name: Deploy the homebrew/ubuntu22.04:master Docker image to GitHub Packages and Docker Hub
        if: >
          github.event_name == 'push' && github.ref == 'refs/heads/master' &&
          matrix.version == '22.04'
        run: |
          docker tag brew "ghcr.io/homebrew/ubuntu22.04:master"
          docker push "ghcr.io/homebrew/ubuntu22.04:master"
          docker tag brew "homebrew/ubuntu22.04:master"
          docker push "homebrew/ubuntu22.04:master"
